package com.attendance.backend.domain.enums;

public enum EventType {
    CHECKIN_QR,
    MARK_MANUAL_PRESENT,
    MARK_MANUAL_LATE,
    MARK_MANUAL_ABSENT,
    MARK_EXCUSED,
    REVERT_FROM_EXCUSED,
    SESSION_OPENED,
    SESSION_CLOSED,

    ABSENCE_REQUEST_CREATED,
    ABSENCE_REQUEST_APPROVED,
    ABSENCE_REQUEST_REJECTED,
    ABSENCE_REQUEST_CANCELLED,
    ABSENCE_REQUEST_REVERTED
}